# Generated by Django 4.2.27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("building_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Immeuble",
                "verbose_name_plural": "Immeubles",
                "db_table": "buildings",
            },
        ),
        migrations.CreateModel(
            name="Contractor",
            fields=[
                ("contractor_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specialties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entrepreneur",
                "verbose_name_plural": "Entrepreneurs",
                "db_table": "contractors",
            },
        ),
        migrations.CreateModel(
            name="IssueCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "sla_hours",
                    models.IntegerField(help_text="Temps de réponse attendu en heures"),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Catégorie de problème",
                "verbose_name_plural": "Catégories de problèmes",
                "db_table": "issue_categories",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("owner_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Propriétaire",
                "verbose_name_plural": "Propriétaires",
                "db_table": "owners",
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                ("part_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("van_inventory", "Inventaire véhicule"),
                            ("central_store", "Entrepôt central"),
                            ("external_supplier", "Fournisseur externe"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Pièce",
                "verbose_name_plural": "Pièces",
                "db_table": "parts",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("tenant_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("has_keys", models.BooleanField(default=False)),
                ("access_notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Locataire",
                "verbose_name_plural": "Locataires",
                "db_table": "tenants",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("emergency", "Urgence"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolu"),
                            ("closed", "Fermé"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("access_windows", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to="core.contractor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="core.issuecategory",
                    ),
                ),
                (
                    "parent_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_tickets",
                        to="core.ticket",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("manager", "Manager"),
                            ("viewer", "Lecteur"),
                        ],
                        default="viewer",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("unit_id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_number", models.CharField(max_length=50)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appartement",
                "verbose_name_plural": "Appartements",
                "db_table": "units",
                "unique_together": {("building", "unit_number")},
            },
        ),
        migrations.CreateModel(
            name="TicketStatusHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("old_status", models.CharField(blank=True, max_length=50, null=True)),
                ("new_status", models.CharField(max_length=50)),
                (
                    "changed_by_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.user",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de statut",
                "verbose_name_plural": "Historiques de statuts",
                "db_table": "ticket_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketPart",
            fields=[
                ("ticket_part_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ticket_usages",
                        to="core.part",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_used",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce utilisée",
                "verbose_name_plural": "Pièces utilisées",
                "db_table": "ticket_parts",
            },
        ),
        migrations.CreateModel(
            name="TicketLaborCost",
            fields=[
                ("labor_id", models.AutoField(primary_key=True, serialize=False)),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=5)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_costs",
                        to="core.contractor",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_costs",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coût de main d'œuvre",
                "verbose_name_plural": "Coûts de main d'œuvre",
                "db_table": "ticket_labor_costs",
            },
        ),
        migrations.CreateModel(
            name="TicketCategoryHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.user",
                    ),
                ),
                (
                    "new_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_category_history",
                        to="core.issuecategory",
                    ),
                ),
                (
                    "old_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_category_history",
                        to="core.issuecategory",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_history",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de catégorie",
                "verbose_name_plural": "Historiques de catégories",
                "db_table": "ticket_category_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="core.unit",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="core.unit",
            ),
        ),
        migrations.CreateModel(
            name="RecurringPattern",
            fields=[
                ("pattern_id", models.AutoField(primary_key=True, serialize=False)),
                ("pattern_description", models.TextField()),
                ("occurrence_count", models.IntegerField(default=1)),
                ("first_occurrence", models.DateTimeField(blank=True, null=True)),
                ("last_occurrence", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_patterns",
                        to="core.building",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_patterns",
                        to="core.issuecategory",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_patterns",
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pattern récurrent",
                "verbose_name_plural": "Patterns récurrents",
                "db_table": "recurring_patterns",
            },
        ),
        migrations.CreateModel(
            name="OnCallRoster",
            fields=[
                ("roster_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backup_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_rosters",
                        to="core.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roster",
                "verbose_name_plural": "Rosters",
                "db_table": "on_call_roster",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("message_text", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="core.contractor",
                    ),
                ),
                (
                    "tenant_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="core.tenant",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.ticket",
                    ),
                ),
                (
                    "user_sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractorAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Accepté"),
                            ("declined", "Refusé"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.contractor",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignation contractor",
                "verbose_name_plural": "Assignations contractors",
                "db_table": "contractor_assignments",
            },
        ),
        migrations.AddField(
            model_name="building",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="core.owner",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("attachment_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor_uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="core.contractor",
                    ),
                ),
                (
                    "tenant_uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="core.tenant",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.ticket",
                    ),
                ),
                (
                    "user_uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "db_table": "attachments",
            },
        ),
    ]
